import React, { useState } from 'react';
import { motion } from 'motion/react';
import { 
  Search, 
  FileCheck2, 
  Clock, 
  CheckCircle2, 
  AlertCircle, 
  Building2, 
  Calendar, 
  User, 
  Download, 
  MessageSquare, 
  ArrowRight,
  ShieldCheck,
  FileText,
  PlaneTakeoff,
  Stamp
} from 'lucide-react';
import { Language } from '../types';
import { translations } from '../data/translations';
import { openWhatsAppInquiry } from '../utils/formatters';

interface ApplicationTrackerProps {
  language: Language;
}

export interface ApplicationRecord {
  refId: string;
  applicantName: string;
  serviceType: 'Visa Consultancy' | 'Umrah Processing';
  destination: string;
  submissionDate: string;
  estimatedCompletion: string;
  overallStatus: 'Approved' | 'In Processing' | 'Ready for Pickup' | 'Document Verification';
  progressPercentage: number;
  passportNumber: string;
  assignedConsultant: string;
  steps: {
    title: string;
    desc: string;
    date: string;
    status: 'completed' | 'current' | 'pending';
  }[];
}

const SAMPLE_RECORDS: Record<string, ApplicationRecord> = {
  'PW-78492': {
    refId: 'PW-78492',
    applicantName: 'Haji Muhammad Farooq & Family',
    serviceType: 'Umrah Processing',
    destination: 'Saudi Arabia (Umrah Visa & Hotel Vouchers)',
    submissionDate: '28 Jan 2026',
    estimatedCompletion: '02 Feb 2026',
    overallStatus: 'Ready for Pickup',
    progressPercentage: 100,
    passportNumber: 'PK-8820****',
    assignedConsultant: 'Tariq Mehmood (North Nazimabad Desk)',
    steps: [
      { title: 'Document Reception & File Audit', desc: 'Original Passports, photos & CNIC verified at Nazimabad office.', date: '28 Jan 2026', status: 'completed' },
      { title: 'MOFA Umrah Portal Entry', desc: 'E-Visa request & insurance policy registered in Saudi Nusuk system.', date: '29 Jan 2026', status: 'completed' },
      { title: 'Hotel & Transport Voucher Locking', desc: 'Clock Tower Swissôtel & luxury bus transport confirmed.', date: '30 Jan 2026', status: 'completed' },
      { title: 'Umrah E-Visa Issued', desc: 'Official Barcode Visa generated by Saudi Ministry.', date: '31 Jan 2026', status: 'completed' },
      { title: 'Passport & Travel Docket Ready', desc: 'Physical passport & travel vouchers ready for pickup at North Nazimabad office.', date: '01 Feb 2026', status: 'completed' }
    ]
  },
  'PW-98214': {
    refId: 'PW-98214',
    applicantName: 'Dr. Syed Hamza Ali',
    serviceType: 'Visa Consultancy',
    destination: 'Turkey Tourist Sticker Visa',
    submissionDate: '22 Jan 2026',
    estimatedCompletion: '06 Feb 2026',
    overallStatus: 'In Processing',
    progressPercentage: 65,
    passportNumber: 'PK-4102****',
    assignedConsultant: 'Usman Ghani (Senior Visa Specialist)',
    steps: [
      { title: 'Document Reception & Audit', desc: 'Bank statement, tax returns & travel itinerary verified.', date: '22 Jan 2026', status: 'completed' },
      { title: 'Cover Letter & Hotel Vouchers', desc: 'Official cover letter & hotel booking voucher attached.', date: '24 Jan 2026', status: 'completed' },
      { title: 'Gerry\'s / Embassy Submission', desc: 'Physical file submitted to Turkish Consulate / Gerry\'s Karachi.', date: '27 Jan 2026', status: 'completed' },
      { title: 'Embassy Review & Decision', desc: 'Application currently undergoing security verification at Turkish Embassy.', date: 'In Progress', status: 'current' },
      { title: 'Passport Stamping & Handover', desc: 'Passport collection notification pending from Embassy.', date: 'Expected 06 Feb', status: 'pending' }
    ]
  },
  'PW-51203': {
    refId: 'PW-51203',
    applicantName: 'Ayesha & Bilal Ahmed',
    serviceType: 'Visa Consultancy',
    destination: 'UAE Dubai 30-Day Tourist Visa',
    submissionDate: '02 Feb 2026',
    estimatedCompletion: '04 Feb 2026',
    overallStatus: 'Approved',
    progressPercentage: 100,
    passportNumber: 'PK-7291****',
    assignedConsultant: 'Rana Asif (GDRFA E-Visa Specialist)',
    steps: [
      { title: 'Passport Scan & Photo Upload', desc: 'High resolution passport scan uploaded to GDRFA Portal.', date: '02 Feb 2026', status: 'completed' },
      { title: 'Immigration Security Clearance', desc: 'Dubai Immigration background verification completed.', date: '03 Feb 2026', status: 'completed' },
      { title: 'E-Visa Approval Issued', desc: 'Official Dubai Tourist E-Visa approved with QR code.', date: '03 Feb 2026', status: 'completed' },
      { title: 'PDF Ticket & Hotel Dispatch', desc: 'Sent to customer via WhatsApp and Email.', date: '03 Feb 2026', status: 'completed' }
    ]
  }
};

export const ApplicationTracker: React.FC<ApplicationTrackerProps> = ({ language }) => {
  const [searchInput, setSearchInput] = useState('PW-78492');
  const [activeRecord, setActiveRecord] = useState<ApplicationRecord | null>(SAMPLE_RECORDS['PW-78492']);
  const [hasSearched, setHasSearched] = useState(true);
  const [errorMsg, setErrorMsg] = useState('');

  const isUrdu = language === 'ur';

  const handleSearch = (codeToSearch?: string) => {
    const code = (codeToSearch || searchInput).trim().toUpperCase();
    if (!code) return;

    setErrorMsg('');
    setHasSearched(true);

    if (SAMPLE_RECORDS[code]) {
      setActiveRecord(SAMPLE_RECORDS[code]);
    } else if (code.startsWith('PW-') || code.length >= 4) {
      // Generate dynamic fallback application tracking data for user's custom reference ID
      const dynamicRec: ApplicationRecord = {
        refId: code,
        applicantName: 'Valued Pak World Client',
        serviceType: code.includes('UMR') ? 'Umrah Processing' : 'Visa Consultancy',
        destination: 'International Travel & Visa Docket',
        submissionDate: '01 Feb 2026',
        estimatedCompletion: '05 Feb 2026',
        overallStatus: 'In Processing',
        progressPercentage: 50,
        passportNumber: 'PK-*****',
        assignedConsultant: 'Pak World Operations Desk',
        steps: [
          { title: 'File Received & Intake Audit', desc: 'Documents logged into Pak World Nazimabad database.', date: '01 Feb 2026', status: 'completed' },
          { title: 'Ministry / Embassy Verification', desc: 'Application actively being processed with authorities.', date: '03 Feb 2026', status: 'current' },
          { title: 'Approval & Stamping', desc: 'Awaiting official visa / barcode release.', date: 'Estimated 05 Feb', status: 'pending' },
          { title: 'Passport Handover', desc: 'Ready for collection at North Nazimabad Office.', date: 'Estimated 06 Feb', status: 'pending' }
        ]
      };
      setActiveRecord(dynamicRec);
    } else {
      setErrorMsg(isUrdu ? 'براہ کرم صحیح ریفرنس نمبر درج کریں (مثلاً PW-78492)' : 'Please enter a valid Reference ID (e.g. PW-78492)');
      setActiveRecord(null);
    }
  };

  const printStatusSummary = () => {
    if (!activeRecord) return;
    window.print();
  };

  return (
    <>
      {/* ------------------------------------------------------------- */}
      {/* 1. OFFSCREEN / PRINTABLE DOCKET (VISIBLE ONLY WHEN PRINTING) */}
      {/* ------------------------------------------------------------- */}
      {activeRecord && (
        <div id="printable-docket-root" className="hidden print:block bg-white text-gray-900 p-8 font-sans border-2 border-gray-900">
          
          {/* Official Agency Header */}
          <div className="flex justify-between items-start border-b-2 border-gray-900 pb-4 mb-6">
            <div>
              <h1 className="text-2xl font-black uppercase tracking-wider text-[#0B1F3A]">
                Pak World Travel & Tours (Pvt) Ltd
              </h1>
              <p className="text-xs text-gray-600 font-bold mt-0.5">
                DTS License No: <span className="text-black font-extrabold">KHI-8842</span> • IATA Accredited Agency: <span className="text-black font-extrabold">27-2 1982 4</span>
              </p>
              <p className="text-[11px] text-gray-500 mt-1">
                Plot B-12, Block A, Near Five Star Chowrangi, North Nazimabad, Karachi, Pakistan
              </p>
              <p className="text-[11px] text-gray-500">
                UAN Phone: +92 21 36678900 | WhatsApp Desk: +92 300 1234567 | Email: info@pakworldtravel.com
              </p>
            </div>

            {/* Official Voucher Badge & Barcode simulation */}
            <div className="text-right shrink-0">
              <div className="border-2 border-gray-900 px-3 py-1 font-mono text-sm font-extrabold bg-gray-100 rounded">
                DOCKET REF: {activeRecord.refId}
              </div>
              <div className="text-[10px] uppercase tracking-widest text-gray-500 mt-1 font-bold">
                Date Issued: {new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}
              </div>
              {/* Simulated QR Barcode */}
              <div className="mt-2 text-[9px] font-mono text-gray-400 border border-gray-300 p-1 rounded inline-block bg-white">
                ||| |||| || |||||| | ||||| {activeRecord.refId}
              </div>
            </div>
          </div>

          <div className="text-center bg-[#0B1F3A] text-white py-2 font-extrabold text-sm uppercase tracking-widest mb-6 rounded">
            Official Application Status & Travel Voucher Docket
          </div>

          {/* Customer & File Summary Table */}
          <div className="grid grid-cols-2 gap-4 mb-6 border border-gray-300 p-4 rounded-lg bg-gray-50">
            <div>
              <p className="text-[10px] uppercase text-gray-500 font-bold">Primary Applicant Name</p>
              <p className="text-sm font-black text-gray-900">{activeRecord.applicantName}</p>
            </div>

            <div>
              <p className="text-[10px] uppercase text-gray-500 font-bold">Service Category</p>
              <p className="text-sm font-black text-[#1E5EFF]">{activeRecord.serviceType}</p>
            </div>

            <div>
              <p className="text-[10px] uppercase text-gray-500 font-bold">Passport / Document Identifier</p>
              <p className="text-xs font-mono font-bold text-gray-800">{activeRecord.passportNumber}</p>
            </div>

            <div>
              <p className="text-[10px] uppercase text-gray-500 font-bold">Target Destination / Package</p>
              <p className="text-xs font-bold text-gray-900">{activeRecord.destination}</p>
            </div>

            <div>
              <p className="text-[10px] uppercase text-gray-500 font-bold">Submission Date</p>
              <p className="text-xs font-semibold text-gray-700">{activeRecord.submissionDate}</p>
            </div>

            <div>
              <p className="text-[10px] uppercase text-gray-500 font-bold">Current Processing Status</p>
              <p className="text-xs font-black uppercase text-emerald-700">{activeRecord.overallStatus} ({activeRecord.progressPercentage}% Completed)</p>
            </div>

            <div>
              <p className="text-[10px] uppercase text-gray-500 font-bold">Assigned Desk Consultant</p>
              <p className="text-xs font-semibold text-gray-800">{activeRecord.assignedConsultant}</p>
            </div>

            <div>
              <p className="text-[10px] uppercase text-gray-500 font-bold">Estimated Passport Handover Date</p>
              <p className="text-xs font-extrabold text-gray-900">{activeRecord.estimatedCompletion}</p>
            </div>
          </div>

          {/* Detailed Stage History */}
          <h3 className="font-extrabold text-xs uppercase tracking-wider text-gray-700 mb-3 border-b border-gray-300 pb-1">
            Application Milestone Progress & Verification Log
          </h3>

          <table className="w-full text-left border-collapse mb-6 text-xs">
            <thead>
              <tr className="bg-gray-200 text-gray-800 uppercase font-black text-[10px] border-b border-gray-400">
                <th className="p-2 w-12 text-center">Stage</th>
                <th className="p-2">Milestone Description</th>
                <th className="p-2 w-28 text-center">Audit Date</th>
                <th className="p-2 w-28 text-center">Status</th>
              </tr>
            </thead>
            <tbody>
              {activeRecord.steps.map((step, idx) => (
                <tr key={idx} className="border-b border-gray-200">
                  <td className="p-2 font-bold text-center border-r border-gray-200">{idx + 1}</td>
                  <td className="p-2 border-r border-gray-200">
                    <p className="font-bold text-gray-900">{step.title}</p>
                    <p className="text-[10px] text-gray-600 mt-0.5">{step.desc}</p>
                  </td>
                  <td className="p-2 text-center font-mono text-[11px] border-r border-gray-200">{step.date}</td>
                  <td className="p-2 text-center font-black uppercase text-[10px]">
                    {step.status === 'completed' ? (
                      <span className="text-emerald-700">COMPLETED</span>
                    ) : step.status === 'current' ? (
                      <span className="text-blue-700">IN PROGRESS</span>
                    ) : (
                      <span className="text-gray-400">PENDING</span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          {/* Verification Stamps & Office Notes */}
          <div className="grid grid-cols-2 gap-6 pt-4 border-t-2 border-gray-900 mt-6 text-xs">
            <div className="border p-3 rounded bg-gray-50">
              <p className="font-extrabold uppercase text-[10px] text-gray-600">Important Collection Notice:</p>
              <ul className="list-disc list-inside text-[10px] text-gray-700 space-y-1 mt-1">
                <li>Original CNIC & physical receipt voucher required at North Nazimabad office pickup.</li>
                <li>Please inspect passport visa sticker & barcode prior to departure from desk.</li>
                <li>For 24/7 airport emergency desk support, call +92 300 1234567.</li>
              </ul>
            </div>

            <div className="border p-3 rounded text-center flex flex-col justify-between h-28">
              <p className="font-bold text-[10px] text-gray-500 uppercase">Pak World Travel Operations Stamp & Officer Signature</p>
              <div className="border-b border-dashed border-gray-400 my-2 mx-8"></div>
              <p className="font-black text-xs text-[#0B1F3A] uppercase">VERIFIED & AUDITED BY NORTH NAZIMABAD DESK</p>
            </div>
          </div>

          <p className="text-[9px] text-center text-gray-400 mt-6 border-t border-gray-200 pt-2">
            This docket is an official computer-generated document issued by Pak World Travel & Tours (Pvt) Ltd Karachi. DTS License No. KHI-8842.
          </p>

        </div>
      )}

      {/* ------------------------------------------------------------- */}
      {/* 2. REGULAR ON-SCREEN UI TRACKER COMPONENT                     */}
      {/* ------------------------------------------------------------- */}
      <div id="tracker" className="bg-[#0B1F3A] text-white py-16 px-4 md:px-8 rounded-[36px] my-12 border border-[#D4AF37]/30 shadow-2xl relative overflow-hidden">

      
      {/* Background Decorative Accents */}
      <div className="absolute -top-24 -right-24 w-96 h-96 bg-[#1E5EFF]/20 rounded-full blur-3xl pointer-events-none"></div>
      <div className="absolute -bottom-24 -left-24 w-96 h-96 bg-[#D4AF37]/10 rounded-full blur-3xl pointer-events-none"></div>

      <div className="max-w-5xl mx-auto relative z-10">

        {/* Section Header */}
        <div className="text-center max-w-2xl mx-auto mb-10">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 bg-[#D4AF37]/20 text-[#D4AF37] border border-[#D4AF37]/40 text-xs font-bold uppercase tracking-widest rounded-full mb-3">
            <ShieldCheck className="w-4 h-4 text-[#D4AF37]" />
            {isUrdu ? 'شفاف طریقہ کار - لائیو ٹریکنگ' : 'Transparent Consultancy Workflow'}
          </div>

          <h2 className="text-3xl sm:text-4xl font-display font-extrabold text-white">
            {isUrdu ? 'اپنی ویزا یا عمرہ فائل کا لائیو اسٹیٹس دیکھیں' : 'Track Visa & Umrah Application Status'}
          </h2>

          <p className="text-gray-300 text-xs sm:text-sm mt-3 leading-relaxed">
            {isUrdu
              ? 'اپنا ریفرنس نمبر درج کریں اور دستاویزات کی تصدیق، سفارتخانہ جمع کرانے اور پاسپورٹ کی تیاری کا لائیو ریکارڈ دیکھیں۔'
              : 'Enter your tracking reference number to inspect real-time progress from document audit to embassy approval and passport pickup.'}
          </p>
        </div>

        {/* Search Bar Container */}
        <div className="bg-white/10 backdrop-blur-md p-4 rounded-[28px] border border-white/15 max-w-2xl mx-auto shadow-xl mb-8">
          <div className="flex flex-col sm:flex-row items-center gap-2">
            <div className="relative flex-1 w-full">
              <Search className="w-5 h-5 text-gray-400 absolute left-4 top-3.5 pointer-events-none" />
              <input
                type="text"
                placeholder={isUrdu ? 'ریفرنس نمبر درج کریں (مثلاً PW-78492)...' : 'Enter Ref No. (e.g. PW-78492, PW-98214)...'}
                value={searchInput}
                onChange={(e) => setSearchInput(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSearch()}
                className="w-full bg-white text-gray-900 rounded-full py-3 pl-12 pr-4 text-xs font-bold focus:outline-none focus:ring-2 focus:ring-[#D4AF37] placeholder:text-gray-400 uppercase tracking-wider"
              />
            </div>
            <button
              onClick={() => handleSearch()}
              className="w-full sm:w-auto px-6 py-3 bg-gradient-to-r from-[#D4AF37] to-amber-500 hover:from-amber-400 hover:to-amber-600 text-[#0B1F3A] font-extrabold text-xs uppercase tracking-wider rounded-full transition-all shadow-lg active:scale-95 shrink-0 flex items-center justify-center gap-1.5"
            >
              <FileCheck2 className="w-4 h-4" />
              <span>{isUrdu ? 'تلاش کریں' : 'Track File'}</span>
            </button>
          </div>

          {/* Quick Demo Reference Pills */}
          <div className="mt-4 pt-3 border-t border-white/10 flex items-center gap-2 flex-wrap">
            <span className="text-[11px] font-semibold text-gray-300">
              {isUrdu ? 'فوری دیکھئے:' : 'Sample Files:'}
            </span>
            {Object.keys(SAMPLE_RECORDS).map((code) => (
              <button
                key={code}
                onClick={() => {
                  setSearchInput(code);
                  handleSearch(code);
                }}
                className={`text-[10px] font-bold px-2.5 py-1 rounded-full border transition-all ${
                  activeRecord?.refId === code
                    ? 'bg-[#D4AF37] text-[#0B1F3A] border-[#D4AF37]'
                    : 'bg-white/10 text-gray-200 border-white/20 hover:bg-white/20'
                }`}
              >
                {code} ({SAMPLE_RECORDS[code].overallStatus})
              </button>
            ))}
          </div>
        </div>

        {errorMsg && (
          <div className="p-4 bg-red-500/20 border border-red-500/40 rounded-2xl text-red-200 text-xs text-center max-w-md mx-auto mb-6 flex items-center justify-center gap-2">
            <AlertCircle className="w-4 h-4 text-red-400" />
            <span>{errorMsg}</span>
          </div>
        )}

        {/* Status Tracker Results Display */}
        {activeRecord && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4 }}
            className="bg-white text-gray-900 rounded-[30px] p-6 md:p-8 shadow-2xl border border-gray-100 relative overflow-hidden"
          >
            {/* Top Status Header Ribbon */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-gray-100 pb-6">
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className="px-3 py-1 bg-[#0B1F3A] text-white text-[11px] font-black uppercase rounded-full tracking-wider">
                    Ref: {activeRecord.refId}
                  </span>
                  <span className="px-3 py-1 bg-[#1E5EFF]/10 text-[#1E5EFF] text-[11px] font-extrabold uppercase rounded-full">
                    {activeRecord.serviceType}
                  </span>
                </div>
                <h3 className="text-xl md:text-2xl font-bold font-display text-[#0B1F3A] mt-2">
                  {activeRecord.applicantName}
                </h3>
                <p className="text-xs text-gray-500 flex items-center gap-1.5 mt-1">
                  <Building2 className="w-3.5 h-3.5 text-[#1E5EFF]" />
                  <span>{activeRecord.destination}</span>
                  <span className="mx-1">•</span>
                  <User className="w-3.5 h-3.5 text-[#D4AF37]" />
                  <span>Desk: {activeRecord.assignedConsultant}</span>
                </p>
              </div>

              <div className="flex flex-col items-start md:items-end shrink-0">
                <span className="text-[10px] uppercase font-bold text-gray-400 tracking-wider">Current Status</span>
                <div className={`mt-1 inline-flex items-center gap-1.5 px-4 py-1.5 rounded-full text-xs font-black uppercase tracking-wider shadow-sm ${
                  activeRecord.overallStatus === 'Approved' || activeRecord.overallStatus === 'Ready for Pickup'
                    ? 'bg-emerald-100 text-emerald-800 border border-emerald-300'
                    : 'bg-amber-100 text-amber-800 border border-amber-300'
                }`}>
                  <Stamp className="w-3.5 h-3.5" />
                  <span>{activeRecord.overallStatus}</span>
                </div>
                <span className="text-[10px] text-gray-400 mt-1">
                  Est. Ready: <strong className="text-gray-700">{activeRecord.estimatedCompletion}</strong>
                </span>
              </div>
            </div>

            {/* Overall Progress Bar */}
            <div className="py-6 border-b border-gray-100">
              <div className="flex justify-between items-center text-xs font-bold text-[#0B1F3A] mb-2">
                <span>Application Lifecycle Progress</span>
                <span className="text-[#1E5EFF] font-black">{activeRecord.progressPercentage}% Completed</span>
              </div>
              <div className="w-full h-3 bg-gray-100 rounded-full overflow-hidden p-0.5 border border-gray-200">
                <div
                  className="h-full bg-gradient-to-r from-[#1E5EFF] to-[#D4AF37] rounded-full transition-all duration-1000 shadow-sm"
                  style={{ width: `${activeRecord.progressPercentage}%` }}
                ></div>
              </div>
            </div>

            {/* Visual Step-by-Step Timeline */}
            <div className="py-6">
              <h4 className="text-xs font-bold uppercase text-gray-400 tracking-wider mb-6 flex items-center gap-1.5">
                <Clock className="w-4 h-4 text-[#1E5EFF]" />
                {isUrdu ? 'مراحل کی تفصیل (Detailed Timeline)' : 'Detailed Processing Stages'}
              </h4>

              <div className="space-y-6 relative before:absolute before:left-[19px] before:top-2 before:bottom-2 before:w-0.5 before:bg-gray-200">
                {activeRecord.steps.map((step, idx) => {
                  const isDone = step.status === 'completed';
                  const isCurrent = step.status === 'current';

                  return (
                    <div key={idx} className="flex items-start gap-4 relative z-10">
                      {/* Step Status Badge Icon */}
                      <div className={`w-10 h-10 rounded-full flex items-center justify-center shrink-0 font-bold text-xs shadow-md ${
                        isDone
                          ? 'bg-emerald-600 text-white'
                          : isCurrent
                          ? 'bg-[#1E5EFF] text-white ring-4 ring-blue-100 animate-pulse'
                          : 'bg-gray-200 text-gray-500'
                      }`}>
                        {isDone ? <CheckCircle2 className="w-5 h-5" /> : idx + 1}
                      </div>

                      {/* Step Content */}
                      <div className={`flex-1 p-4 rounded-[20px] border transition-all ${
                        isCurrent
                          ? 'bg-blue-50/70 border-[#1E5EFF]/30 shadow-md'
                          : isDone
                          ? 'bg-emerald-50/40 border-emerald-100'
                          : 'bg-gray-50 border-gray-100'
                      }`}>
                        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-1 mb-1">
                          <h5 className="font-bold text-sm text-[#0B1F3A] flex items-center gap-2">
                            {step.title}
                            {isCurrent && (
                              <span className="px-2 py-0.5 bg-[#1E5EFF] text-white text-[9px] font-black uppercase rounded-full">
                                Active Step
                              </span>
                            )}
                          </h5>
                          <span className="text-[10px] font-semibold text-gray-400 bg-white px-2 py-0.5 rounded-full border border-gray-200 w-fit">
                            {step.date}
                          </span>
                        </div>
                        <p className="text-xs text-gray-600 leading-relaxed">
                          {step.desc}
                        </p>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Bottom Actions Bar */}
            <div className="pt-6 border-t border-gray-100 flex flex-col sm:flex-row items-center justify-between gap-4 bg-[#F6F8FC] -mx-6 -mb-6 md:-mx-8 md:-mb-8 p-6 rounded-b-[30px]">
              <div className="text-xs text-gray-600 flex items-center gap-2">
                <ShieldCheck className="w-4 h-4 text-emerald-600 shrink-0" />
                <span>
                  {isUrdu ? 'محفوظ ترین سسٹم - پاک ورلڈ نارتھ ناظم آباد کراچی' : 'Official Pak World Verified Docket • North Nazimabad Office'}
                </span>
              </div>

              <div className="flex items-center gap-3 w-full sm:w-auto">
                <button
                  onClick={() => openWhatsAppInquiry(`Assalamu Alaikum Pak World Team! I am checking status of my file Reference No: ${activeRecord.refId} (${activeRecord.applicantName}). Please update me.`)}
                  className="flex-1 sm:flex-none px-4 py-2.5 bg-[#25D366] hover:bg-emerald-600 text-white font-bold text-xs uppercase rounded-xl flex items-center justify-center gap-1.5 transition-all shadow-md active:scale-95"
                >
                  <MessageSquare className="w-4 h-4" />
                  <span>{isUrdu ? 'واٹس ایپ اپ ڈیٹ' : 'WhatsApp Agent'}</span>
                </button>

                <button
                  onClick={printStatusSummary}
                  className="flex-1 sm:flex-none px-4 py-2.5 bg-[#0B1F3A] hover:bg-[#1E5EFF] text-white font-bold text-xs uppercase rounded-xl flex items-center justify-center gap-1.5 transition-all shadow-md active:scale-95"
                >
                  <Download className="w-4 h-4" />
                  <span>{isUrdu ? 'پرنٹ لاگ' : 'Print Docket'}</span>
                </button>
              </div>
            </div>

          </motion.div>
        )}

      </div>
    </div>
    </>
  );
};
